# Generated by Django 5.0.2 on 2024-03-11 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_number", models.IntegerField(verbose_name="Номер договора")),
                (
                    "date",
                    models.DateField(
                        default="2024-01-01", verbose_name="Дата отправки из склада"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expenditure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_number", models.IntegerField(verbose_name="Номер договора")),
                (
                    "date",
                    models.DateField(
                        default="2024-01-01", verbose_name="Дата отправки из склада"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название группы"),
                ),
                ("info", models.CharField(max_length=250, verbose_name="Информация")),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                ("lastname", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "middlename",
                    models.CharField(max_length=50, verbose_name="Отчество"),
                ),
                (
                    "number",
                    models.CharField(
                        default="", max_length=12, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Manager",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Название")),
                ("size", models.CharField(max_length=10, verbose_name="Размер")),
                (
                    "manufacturer",
                    models.CharField(max_length=100, verbose_name="Производитель"),
                ),
                (
                    "country_from",
                    models.CharField(
                        max_length=100, verbose_name="Страна производство"
                    ),
                ),
                (
                    "group_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
            },
        ),
        migrations.CreateModel(
            name="Offs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(max_length=50, verbose_name="Количество"),
                ),
                (
                    "reason",
                    models.CharField(max_length=250, verbose_name="Причина списание"),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expenditure_add",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(max_length=50, verbose_name="Количество"),
                ),
                (
                    "price",
                    models.IntegerField(max_length=50, verbose_name="Цена за 1 штук"),
                ),
                (
                    "exp_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.expenditure",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Coming_add",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(max_length=50, verbose_name="Количество"),
                ),
                (
                    "price",
                    models.IntegerField(max_length=50, verbose_name="Цена за 1 штук"),
                ),
                (
                    "com_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.coming",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "address",
                    models.CharField(max_length=150, verbose_name="Адрес поставщика"),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.manager",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="coming",
            name="prov_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="warehouse.provider"
            ),
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=50, verbose_name="Город")),
                (
                    "address",
                    models.CharField(max_length=150, verbose_name="Адрес точки"),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.manager",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="expenditure",
            name="rec_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="warehouse.recipient"
            ),
        ),
        migrations.CreateModel(
            name="Secretary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                ("lastname", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "middlename",
                    models.CharField(max_length=50, verbose_name="Отчество"),
                ),
                (
                    "number",
                    models.CharField(
                        default="", max_length=12, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "email",
                    models.CharField(default="", max_length=50, verbose_name="Почта"),
                ),
                (
                    "dateofbirth",
                    models.DateField(
                        blank=True,
                        default="1900-01-01",
                        null=True,
                        verbose_name="Дата рождения",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Secretarie",
            },
        ),
        migrations.AddField(
            model_name="expenditure",
            name="sec_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="warehouse.secretary"
            ),
        ),
        migrations.AddField(
            model_name="coming",
            name="sec_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="warehouse.secretary"
            ),
        ),
    ]
