# Generated by Django 5.0.2 on 2024-03-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(default="", max_length=50, verbose_name="Цвет"),
        ),
    ]
