# Generated by Django 5.0.2 on 2024-03-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0002_product_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=0, verbose_name="Количество"),
        ),
    ]
