# Generated by Django 5.0.2 on 2024-03-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0003_product_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coming_add",
            name="price",
            field=models.IntegerField(default=0, verbose_name="Цена за 1 штук"),
        ),
        migrations.AlterField(
            model_name="coming_add",
            name="quantity",
            field=models.IntegerField(default=0, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="expenditure_add",
            name="price",
            field=models.IntegerField(default=0, verbose_name="Цена за 1 штук"),
        ),
        migrations.AlterField(
            model_name="expenditure_add",
            name="quantity",
            field=models.IntegerField(default=0, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="offs",
            name="quantity",
            field=models.IntegerField(default=0, verbose_name="Количество"),
        ),
    ]
