# Generated by Django 5.0.2 on 2024-03-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0004_alter_coming_add_price_alter_coming_add_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offs",
            name="created_at",
            field=models.DateField(default="2024-01-01", verbose_name="Дата списания"),
        ),
    ]
