# Generated by Django 5.0.2 on 2024-03-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0005_offs_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coming",
            name="date",
            field=models.DateField(
                default="2024-01-01", verbose_name="Дата прихода на склада"
            ),
        ),
    ]
